export const ADD_CONVERSATION = 'ADD_CONVERSATION';
export const SET_ACTIVE_CONVERSATION_ID = 'SET_ACTIVE_CONVERSATION_ID';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const ADD_MESSAGE_TO_CONVERSATION = 'ADD_MESSAGE_TO_CONVERSATION';
export const UPDATE_MESSAGE_IN_CONVERSATION = 'UPDATE_MESSAGE_IN_CONVERSATION';
export const DELETE_CHAT_MESSAGES = 'DELETE_CHAT_MESSAGES'